### ISSUE TITLE
Big documentation clean up.

### ISSUE THREAD

**Issue by jhkennedy** [LIVVkit/LIVVkit#2]
There are some inconsistencies and missing information in the wiki that should be cleaned up pre-release. 

Note: I'm working on these -- using this issue to keep track, and solicit input as needed. 

[ ] Discussion of verification and validation in general:
- Terminology is a little mixed up -- need to go decide what we mean by _code verification_, _code validation_, _performance validation_, and _scientific validation_ 
- _Code Validation_ section refers to what things done in our `verification` code. This is inconsistent. 

[ ] User workflow
-  Basic workflow for users -- perform an initial verification of install from benchmark data

[ ] Devloper workflow
- perform _code verification_, _code validation_, and _performance validation_ across commits (pull requests)

[ ] Scientist workflow
- perform _scientific validation_, possibly in conjunction with _performance validation_ (This is easy, as we don't currently have this capability)

[ ] include a development road map which describes our developmental goals.

**Comment by jhkennedy** [comment]
Alright, I've been thinking quite a bit about the four V&V terms _code verification_, _code validation_, _performance validation_, and _scientific validation_. 

Right now, we _imply_ that verification and validation consists of:
- Code verification -- which we define as:
  - Ensuring correctness of: source code, numerical algorithms, model reliability
- Code validation -- which we define as:
  -  Determining whether the software is being used meets the design specifications
- Performance validation -- which we define as:
  - The process of determining the computational cost of a model and its components (penalty for adding a new component)
- Scientific validation -- which we don't define (in the wiki) currently. 

---

I think we'd be better off describing V&V as really two sets of complementary V&V processes. That is:

Model V&V:
- Numerical verification -- which is:
  - Comparing the _approximate numerical_ prediction against the _analytical_ prediction of our particular mathematical model(s). This is inherently a **math** problem (are we solving the equation correctly?).
- Physical validation -- which is:
  - Comparing the _model_ prediction against _natural_ phenomena. This is inherently a **physics** problem (are we using the right physics?). 

and Software V&V:
- Code verification -- which is:
  - the model implementation and it's associated data accurately represents the developers' specifications. 
- Performance validation -- which is:
  - how well the model is able to be used as intended. 

The _Model V&V_ set describes V&V as you would expect to see if from mathematical/physical/scientific standpoint, while the _Software V&V_ describes V&V as you would expect from the software development standpoint. (Note that Software V&V is a blend of the "software engineering" and "modeling and simulation engineering" definition.)

I think breaking it apart like this will help us describe what LIVV does, what LIVV is intended to do, and prevent miss communication of ideas. Also, conveniently, this better fits in with our current code layout. That is, LIVV currently:
- Assumes that the developers have performed the _numerical verification_ (not in our code -- could be as `numerics`)
- Does not perform _physical validation_ (will be in our code as `validation`)
- Uses b4b testing and model output analysis to compare a _numerically verified_ (benchmark) dataset against a _model generated_ (test) dataset. This is _code verification_. (in our code as `verification`)
- Provides some basic _performance validation_ by providing some weak and strong scaling information. (in our code as `performance`)

---

At least this is how it makes sense to me to describe our current capabilities, goals, and use-cases (workflows). 

Does that sound correct/appropriate/good @arbennett, @kevans32, @stephenprice, @matthewhoffman?

**Comment by jhkennedy** [comment]
This is also similar to what is described in [this PDF](http://www.ltas-vis.ulg.ac.be/cmsms/uploads/File/LosAlamos_VerificationValidation.pdf) from LANL.

**Comment by arbennett** [comment]
I think this fits our use-cases much better than the way we have it laid out in the Wiki currently.

**Comment by stephenprice** [comment]
Hi Joe. This sounds good to me. I think the distinction between the software and scientific understanding of V&V. One slight concern is that currently, we have very few tests that really satisfy the "numerical verification" item. That is, most of our "verification" is done against benchmarks (of our own or from the wider community) as opposed to against analytical solutions. Right now, from our standard suite of tests, I think only Halfar and the stream test case have analytical solutions.

**Comment by jhkennedy** [comment]
@stephenprice, I agree with your concern. I plan on putting some more "numerical verification" capabilities on our development road map. I'll put in a description of community-style benchmarks as well -- didn't think about how to fit those in, but they are important to discuss. Thanks!

Both V&Vs will have their own wiki pages that will discuss these in a bit more detail. 

It seems like we are okay with this style of description, so I'm going to close this issue.
