### ISSUE TITLE
Refactor LIVVkit elements

### ISSUE THREAD

**Issue by arbennett** [LIVVkit/LIVVkit#20]
Jupyter notebooks can render custom html if a class implements the `_repr_html` method. If the element definitions were refactored as objects they could include `_repr_html` methods which would just call the relevant javascript functions inside a script tag.  

If this was done I think the TeX helper module could be merged into the main element subclasses as well.

@jhkennedy I just randomly had this idea after learning about `_repr_html` and figured I'd throw it out there.  Feel free to close if you don't think it's a good/feasible addition.

**Comment by jhkennedy** [comment]
@arbennett this is a great idea; some of the elements have been getting more complex, so the shift to class elements was likely going to be happening anyways.

**Comment by jhkennedy** [comment]
Actually, along this line, I was also considering shifting the website generation to a static site generator -- possibly just using sphinx (since we use it for docs) or something like pelican/lektor. Either way, having element classes and implementing some `_repr_*` methods will likely happen.
